# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 462c5b81043fe47ac68db7cb2d9f53aeb507f502885912e21c233fce087fe79d498d1fc9d493471884b078ab035e8fca2f3aa4d886b697ed5142f3de976bda7f

test:
  secret_key_base: eaf6cc6b918f4e2204941f05c6fa557eb2ab2e4013a5a888041ebf0443f4c40d778e4058ffd8ddbba905cc93d8f2701769537e4f2a87d48ef9e0b3f5ddee113a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
